(*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 *)

let rec solve ?num1:((num1: int) = 1) ?num2:((num2: int) = 2)
    ?sum:((sum: int) = 0) () =
  if num2 > 4000000 then sum
  else if num2 mod 2 == 0 then
    solve ~num1:num2 ~num2:(num1 + num2) ~sum:(sum + num2) ()
  else solve ~num1:num2 ~num2:(num1 + num2) ~sum ()

let result = solve ()

;; print_int result
